insert into CARRIER (name_cyrilic, carrierplaceid) values ('ИДО ТОУРС - ТЕТОВО', '1');
insert into CARRIER (name_cyrilic, carrierplaceid) values ('Општина Куманово и Општина Старо Нагоричане', '1');
insert into CARRIER (name_cyrilic, carrierplaceid) values ('ПЕЛАГОНИЈА ТРАНС АД ПРИЛЕП', '1');
insert into CARRIER (name_cyrilic, carrierplaceid) values ('МАРЈАН ТУРС ДООЕЛ - ПРОБИШТИП', '1');
insert into CARRIER (name_cyrilic, carrierplaceid) values ('АНДОН КОМПАНИ - ПЕХЧЕВО', '1');
insert into CARRIER (name_cyrilic, carrierplaceid) values ('ШТУЗ ПАТНИЧКИ - КУМАНОВО', '1');
insert into CARRIER (name_cyrilic, carrierplaceid) values ('ДАЈО ТУРС ДООЕЛ - с.Пепелиште, Неготино', '1');
insert into CARRIER (name_cyrilic, carrierplaceid) values ('БОБИ-ТУРС - БИТОЛА', '1');
insert into CARRIER (name_cyrilic, carrierplaceid) values ('ЈОЦО ТУРС МС - КУМАНОВО', '1');
insert into CARRIER (name_cyrilic, carrierplaceid) values ('ТРАНСБАЛКАН - ГЕВГЕЛИЈА', '1');
insert into CARRIER (name_cyrilic, carrierplaceid) values ('АД ГАЛЕБ - ОХРИД', '1');
insert into CARRIER (name_cyrilic, carrierplaceid) values ('Општина Велес и Општина Лозово', '1');
insert into CARRIER (name_cyrilic, carrierplaceid) values ('НОТА-МИ - с.ЛОЈАНЕ', '1');
insert into CARRIER (name_cyrilic, carrierplaceid) values ('Општина Велес и Општина Чашка', '1');
insert into CARRIER (name_cyrilic, carrierplaceid) values ('ОМЕГА 2006 ДООЕЛ - ОХРИД', '1');
insert into CARRIER (name_cyrilic, carrierplaceid) values ('АМИГО КОМПАНИ  ГЕВГЕЛИЈА', '1');
insert into CARRIER (name_cyrilic, carrierplaceid) values ('МАРИО ТРАНС-САМОКОВ', '1');
insert into CARRIER (name_cyrilic, carrierplaceid) values ('СТРУМИЦА ЕКСПРЕС СТРУМИЦА', '1');
insert into CARRIER (name_cyrilic, carrierplaceid) values ('ЏЕКИ ТУРС ЕКСПРЕС ДООЕЛ - ДЕБАР', '1');
insert into CARRIER (name_cyrilic, carrierplaceid) values ('Општина Охрид и Општина Дебарца', '1');
insert into CARRIER (name_cyrilic, carrierplaceid) values ('ИНА П КОМПАНИ-ОХРИД', '1');
insert into CARRIER (name_cyrilic, carrierplaceid) values ('ФИКРЕТ ТУРИЗАМ во кооперација со ШТУЗ ПАТНИЧКИ', '1');
insert into CARRIER (name_cyrilic, carrierplaceid) values ('ДООЕЛ ЛАСТА ТУРС-ДЕБРЕШТЕ', '1');
insert into CARRIER (name_cyrilic, carrierplaceid) values ('Општина Гостивар и Општина Маврово и Ростуша', '1');
insert into CARRIER (name_cyrilic, carrierplaceid) values ('СТЕЛА БУС ДООЕЛ, с.Обршани, Кривогаштани', '1');
insert into CARRIER (name_cyrilic, carrierplaceid) values ('Општина Дебар и Општина Маврово и Ростуша', '1');
insert into CARRIER (name_cyrilic, carrierplaceid) values ('СПОГОДБИ ПОМЕЃУ ОПШТИНИТЕ ЗА ЗАЕДНИЧКО ОРГАНИЗИРАЊЕ НА ЛИНИСКИ ПРЕВОЗ НА ПАТНИЦИ', '1');
insert into CARRIER (name_cyrilic, carrierplaceid) values ('ЕУРОПА БУС ДООЕЛ - СТРУГА', '1');
insert into CARRIER (name_cyrilic, carrierplaceid) values ('ДЕЛУКС ТУРС - КУМАНОВО', '1');
insert into CARRIER (name_cyrilic, carrierplaceid) values ('МЕРЏО КОМПАНИ с.НИКУШТАК - ЛИПКОВО', '1');
insert into CARRIER (name_cyrilic, carrierplaceid) values ('ТРАНСКОП - БИТОЛА', '1');
insert into CARRIER (name_cyrilic, carrierplaceid) values ('Општина Прилеп и Општина Долнени', '1');
insert into CARRIER (name_cyrilic, carrierplaceid) values ('ЕДИ-ТУРС ДООЕЛ - с.Оризаре, Липково', '1');
insert into CARRIER (name_cyrilic, carrierplaceid) values ('ЕКО ТОУРС - ТЕТОВО', '1');
insert into CARRIER (name_cyrilic, carrierplaceid) values ('РЕИС-К - СВЕТИ НИКОЛЕ', '1');
insert into CARRIER (name_cyrilic, carrierplaceid) values ('ЕКСТРА 03 - КАВАДАРЦИ', '1');
insert into CARRIER (name_cyrilic, carrierplaceid) values ('ДООЕЛ СПРИЈА-ВЕВЧАНИ', '1');
insert into CARRIER (name_cyrilic, carrierplaceid) values ('СКОРПИОН М-К - КРУШЕВО', '1');
insert into CARRIER (name_cyrilic, carrierplaceid) values ('СТЕВАНИ-БЕНЗ', '1');
insert into CARRIER (name_cyrilic, carrierplaceid) values ('САМ-ВЕЛ КОМПАНИ - КАВАДАРЦИ', '1');
insert into CARRIER (name_cyrilic, carrierplaceid) values ('ВАКЧАРЕ-с.РАДОЛИШТА, СТРУГА', '1');
insert into CARRIER (name_cyrilic, carrierplaceid) values ('КЛАСИК КОМПАНИ-СТРУГА АД ГАЛЕБ-ОХРИД (во кооперација)', '1');
insert into CARRIER (name_cyrilic, carrierplaceid) values ('МАРИЈА ТРАНС - БИТОЛА', '1');
insert into CARRIER (name_cyrilic, carrierplaceid) values ('ОЛИ-ТРАВЕЛ', '1');
insert into CARRIER (name_cyrilic, carrierplaceid) values ('АТП ПРОЛЕТЕР - КРИВА ПАЛАНКА', '1');
insert into CARRIER (name_cyrilic, carrierplaceid) values ('МЕТРО ТРАНС - с.ДЕБРЕШТА ДОЛНЕНИ', '1');
insert into CARRIER (name_cyrilic, carrierplaceid) values ('ЕУРО БУС - СТРУГА', '1');
insert into CARRIER (name_cyrilic, carrierplaceid) values ('ДОКО-ТРАНС - СТРУГА', '1');
insert into CARRIER (name_cyrilic, carrierplaceid) values ('БЕРОВО ТРАНС - БЕРОВО', '1');
insert into CARRIER (name_cyrilic, carrierplaceid) values ('УНИ ТОУРС ДОО - ПРИЛЕП', '1');
insert into CARRIER (name_cyrilic, carrierplaceid) values ('СОТКА БУС ДООЕЛ - с.Горобинци, Свети Николе', '1');
insert into CARRIER (name_cyrilic, carrierplaceid) values ('МАМЛИ ТРАВЕЛ ДООЕЛ - КУМАНОВО', '1');
insert into CARRIER (name_cyrilic, carrierplaceid) values ('ЃОКО ГЛИГОР ШОНТЕВСКИ - БЕРОВО ', '1');
insert into CARRIER (name_cyrilic, carrierplaceid) values ('АМИГО КОМПАНИ ДОО - ГЕВГЕЛИЈА', '1');
insert into CARRIER (name_cyrilic, carrierplaceid) values ('МЕТРО ТРАНС ДООЕЛ - с.Дебреште, Долнени', '1');
insert into CARRIER (name_cyrilic, carrierplaceid) values ('РУЛЕ ТУРС - СКОПЈЕ', '1');
insert into CARRIER (name_cyrilic, carrierplaceid) values ('СКУДРИЊЕ ТРАНС', '1');
insert into CARRIER (name_cyrilic, carrierplaceid) values ('Општина Конче и Општина Радовиш', '1');
insert into CARRIER (name_cyrilic, carrierplaceid) values ('ПЕЛАГОНИЈА ТРАНС А.Д - ПРИЛЕП', '1');
insert into CARRIER (name_cyrilic, carrierplaceid) values ('Т-СТЕФАНИ ДООЕЛ - с.Пирава, Валандово', '1');
insert into CARRIER (name_cyrilic, carrierplaceid) values ('ДЕЛФИНА ТУРС ДООЕЛ - СКОПЈЕ', '1');
insert into CARRIER (name_cyrilic, carrierplaceid) values ('БАЛКАН - ТОУРС ДООЕЛ - с.Ростуша, Маврово', '1');
insert into CARRIER (name_cyrilic, carrierplaceid) values ('ДОРИ - ГЕВГЕЛИЈА', '1');
insert into CARRIER (name_cyrilic, carrierplaceid) values ('РАДИКА ПРЕВОЗ - НСР ДООЕЛ - с.Баланци, Центар Жупа', '1');
insert into CARRIER (name_cyrilic, carrierplaceid) values ('ДУРМО ТУРС - ГОСТИВАР', '1');
insert into CARRIER (name_cyrilic, carrierplaceid) values ('ЏЕМ ТУРС - с.Породин БИТОЛА', '1');
insert into CARRIER (name_cyrilic, carrierplaceid) values ('ЕУРО ЛИНИА - с.ЛИВАДА, СТРУГА', '1');
insert into CARRIER (name_cyrilic, carrierplaceid) values ('УНИК АР ТУРС ДООЕЛ - ДЕБАР', '1');
insert into CARRIER (name_cyrilic, carrierplaceid) values ('ФИЛЕ ТУРС ДООЕЛ - КРАТОВО', '1');
insert into CARRIER (name_cyrilic, carrierplaceid) values ('ЦОБИ СМ ДООЕЛ - БЕРОВО', '1');
insert into CARRIER (name_cyrilic, carrierplaceid) values ('Општина Тетово Општина Теарце, Општина Јегуновце, Општина Желино, Општина Брвеница и Општина Боговиње', '1');
insert into CARRIER (name_cyrilic, carrierplaceid) values ('БИСЕР-ПРОМ - СКОПЈЕ', '1');
insert into CARRIER (name_cyrilic, carrierplaceid) values ('КАМ СМАРК ДОО - КАВАДАРЦИ', '1');
insert into CARRIER (name_cyrilic, carrierplaceid) values ('ДЕ - КА - ДЕМИР КАПИЈА', '1');
insert into CARRIER (name_cyrilic, carrierplaceid) values ('КЛАСИК КОМПАНИ ДООЕЛ - СТРУГА', '1');
insert into CARRIER (name_cyrilic, carrierplaceid) values ('ДОРА-ТУРИСТ ДООЕЛ - Куманово', '1');
insert into CARRIER (name_cyrilic, carrierplaceid) values ('БИСЕР ПРОМ - Скопје', '1');
insert into CARRIER (name_cyrilic, carrierplaceid) values ('ХИСАРИ-ГД ДООЕЛ - ДЕБАР', '1');
insert into CARRIER (name_cyrilic, carrierplaceid) values ('ШТУЗ ПАТНИЧКИ  КУМАНОВО во кооперација со ФИКРЕТ ТУРИЗАМ ', '1');
insert into CARRIER (name_cyrilic, carrierplaceid) values ('РАМА ТУРС - с.ДЕБРЕШТЕ', '1');
insert into CARRIER (name_cyrilic, carrierplaceid) values ('СТРУМИЦА ЕКСПРЕС - СТРУМИЦА', '1');
insert into CARRIER (name_cyrilic, carrierplaceid) values ('ЕУРО ТУРИСТ ДООЕЛ - ГОСТИВАР', '1');
insert into CARRIER (name_cyrilic, carrierplaceid) values ('АД ГАЛЕБ-ОХРИД (во кооперација) со КЛАСИК КОМПАНИ', '1');
insert into CARRIER (name_cyrilic, carrierplaceid) values ('АВТО АТОМ - КОЧАНИ', '1');
insert into CARRIER (name_cyrilic, carrierplaceid) values ('АНДОН КОМПАНИ ДОО - ПЕХЧЕВО', '1');
insert into CARRIER (name_cyrilic, carrierplaceid) values ('ПАН ПРОМЕТ - ВЕЛЕС', '1');
insert into CARRIER (name_cyrilic, carrierplaceid) values ('АРИ ДИЕ 2014 ДООЕЛ - СКОПЈЕ', '1');
insert into CARRIER (name_cyrilic, carrierplaceid) values ('Општина Прилеп и Општина Кривогаштани', '1');
insert into CARRIER (name_cyrilic, carrierplaceid) values ('СИМПЛИ КОМ - КУМАНОВО', '1');
insert into CARRIER (name_cyrilic, carrierplaceid) values ('АВТО АТОМ - КОЧАНИ', '1');
insert into CARRIER (name_cyrilic, carrierplaceid) values ('ЦРВО ЕКСПРЕС ДОО - ШТИП', '1');
insert into CARRIER (name_cyrilic, carrierplaceid) values ('АВТО АТОМ ДОО - КОЧАНИ', '1');
insert into CARRIER (name_cyrilic, carrierplaceid) values ('ЧИКРИ ТРЕЈД - ДЕБАР', '1');
insert into CARRIER (name_cyrilic, carrierplaceid) values ('ДООЕЛ ЛАСТА ТУРС - ДЕБРЕШТЕ', '1');
insert into CARRIER (name_cyrilic, carrierplaceid) values ('СЕНАД ТОУРС - с.ВЕЛЕШТА, СТРУГА', '1');
insert into CARRIER (name_cyrilic, carrierplaceid) values ('НАСИР ТУРИЗАМ - ГОСТИВАР', '1');
insert into CARRIER (name_cyrilic, carrierplaceid) values ('МАРТИНОСКИ - СТРУГА', '1');
insert into CARRIER (name_cyrilic, carrierplaceid) values ('ЈОЦО-ТУРС МС ДОО - КУМАНОВО', '1');
insert into CARRIER (name_cyrilic, carrierplaceid) values ('БАБУНА ПРЕВОЗ - ВЕЛЕС', '1');
insert into CARRIER (name_cyrilic, carrierplaceid) values ('ЃОКО ТРАНС - КРУШЕВО', '1');
