insert into PLACE (name_cyrilic, countryid) values ('Стење', '1');
insert into PLACE (name_cyrilic, countryid) values ('Жван', '1');
insert into PLACE (name_cyrilic, countryid) values ('Кочани', '1');
insert into PLACE (name_cyrilic, countryid) values ('Раковец', '1');
insert into PLACE (name_cyrilic, countryid) values ('Неготино', '1');
insert into PLACE (name_cyrilic, countryid) values ('Велебрдо', '1');
insert into PLACE (name_cyrilic, countryid) values ('Делчево', '1');
insert into PLACE (name_cyrilic, countryid) values ('Србјани', '1');
insert into PLACE (name_cyrilic, countryid) values ('Свети Николе', '1');
insert into PLACE (name_cyrilic, countryid) values ('Липково', '1');
insert into PLACE (name_cyrilic, countryid) values ('Жировница', '1');
insert into PLACE (name_cyrilic, countryid) values ('Стримница', '1');
insert into PLACE (name_cyrilic, countryid) values ('Волковија', '1');
insert into PLACE (name_cyrilic, countryid) values ('Tеново', '1');
insert into PLACE (name_cyrilic, countryid) values ('Гостивар', '1');
insert into PLACE (name_cyrilic, countryid) values ('Г.Лешница', '1');
insert into PLACE (name_cyrilic, countryid) values ('Кривогаштани', '1');
insert into PLACE (name_cyrilic, countryid) values ('Копанце', '1');
insert into PLACE (name_cyrilic, countryid) values ('Богданци', '1');
insert into PLACE (name_cyrilic, countryid) values ('Црнилиште', '1');
insert into PLACE (name_cyrilic, countryid) values ('Г.Липовиќ', '1');
insert into PLACE (name_cyrilic, countryid) values ('Блаце', '1');
insert into PLACE (name_cyrilic, countryid) values ('Слатино', '1');
insert into PLACE (name_cyrilic, countryid) values ('Бајловце', '1');
insert into PLACE (name_cyrilic, countryid) values ('Габревци', '1');
insert into PLACE (name_cyrilic, countryid) values ('Крива Паланка', '1');
insert into PLACE (name_cyrilic, countryid) values ('Добарце', '1');
insert into PLACE (name_cyrilic, countryid) values ('Скопје', '1');
insert into PLACE (name_cyrilic, countryid) values ('М.Каменица', '1');
insert into PLACE (name_cyrilic, countryid) values ('Ношпал', '1');
insert into PLACE (name_cyrilic, countryid) values ('Стар Дојран', '1');
insert into PLACE (name_cyrilic, countryid) values ('Центар  Жупа', '1');
insert into PLACE (name_cyrilic, countryid) values ('Желино', '1');
insert into PLACE (name_cyrilic, countryid) values ('Мусинци', '1');
insert into PLACE (name_cyrilic, countryid) values ('Лојане', '1');
insert into PLACE (name_cyrilic, countryid) values ('Татариновац', '1');
insert into PLACE (name_cyrilic, countryid) values ('Долнени', '1');
insert into PLACE (name_cyrilic, countryid) values ('Јажинце', '1');
insert into PLACE (name_cyrilic, countryid) values ('Липец', '1');
insert into PLACE (name_cyrilic, countryid) values ('с.Житоште', '1');
insert into PLACE (name_cyrilic, countryid) values ('Прилеп', '1');
insert into PLACE (name_cyrilic, countryid) values ('Балинци', '1');
insert into PLACE (name_cyrilic, countryid) values ('Брвеница', '1');
insert into PLACE (name_cyrilic, countryid) values ('М.Брод', '1');
insert into PLACE (name_cyrilic, countryid) values ('Требиште', '1');
insert into PLACE (name_cyrilic, countryid) values ('Злетово', '1');
insert into PLACE (name_cyrilic, countryid) values ('Куманово', '1');
insert into PLACE (name_cyrilic, countryid) values ('Раотинце', '1');
insert into PLACE (name_cyrilic, countryid) values ('Лубница', '1');
insert into PLACE (name_cyrilic, countryid) values ('Штип', '1');
insert into PLACE (name_cyrilic, countryid) values ('Демир Капија', '1');
insert into PLACE (name_cyrilic, countryid) values ('Локвени', '1');
insert into PLACE (name_cyrilic, countryid) values ('Жиганци', '1');
insert into PLACE (name_cyrilic, countryid) values ('Виница', '1');
insert into PLACE (name_cyrilic, countryid) values ('Теранци', '1');
insert into PLACE (name_cyrilic, countryid) values ('Нераште', '1');
insert into PLACE (name_cyrilic, countryid) values ('Аџиевци', '1');
insert into PLACE (name_cyrilic, countryid) values ('Ранковце', '1');
insert into PLACE (name_cyrilic, countryid) values ('Маврово', '1');
insert into PLACE (name_cyrilic, countryid) values ('Битуше', '1');
insert into PLACE (name_cyrilic, countryid) values ('Пирок', '1');
insert into PLACE (name_cyrilic, countryid) values ('Ресен', '1');
insert into PLACE (name_cyrilic, countryid) values ('Пашино Рувци', '1');
insert into PLACE (name_cyrilic, countryid) values ('Дебреште', '1');
insert into PLACE (name_cyrilic, countryid) values ('Блатец', '1');
insert into PLACE (name_cyrilic, countryid) values ('Видовиште', '1');
insert into PLACE (name_cyrilic, countryid) values ('Белчишта', '1');
insert into PLACE (name_cyrilic, countryid) values ('Јасеново', '1');
insert into PLACE (name_cyrilic, countryid) values ('Десово', '1');
insert into PLACE (name_cyrilic, countryid) values ('Довезанце', '1');
insert into PLACE (name_cyrilic, countryid) values ('Дедино', '1');
insert into PLACE (name_cyrilic, countryid) values ('Ростуше', '1');
insert into PLACE (name_cyrilic, countryid) values ('Истибање', '1');
insert into PLACE (name_cyrilic, countryid) values ('Ларце', '1');
insert into PLACE (name_cyrilic, countryid) values ('(преку Агино Село)', '1');
insert into PLACE (name_cyrilic, countryid) values ('Јегуновце', '1');
insert into PLACE (name_cyrilic, countryid) values ('Горно Јаболчиште', '1');
insert into PLACE (name_cyrilic, countryid) values ('Струмица', '1');
insert into PLACE (name_cyrilic, countryid) values ('Чашка', '1');
insert into PLACE (name_cyrilic, countryid) values ('Битола', '1');
insert into PLACE (name_cyrilic, countryid) values ('Присојница', '1');
insert into PLACE (name_cyrilic, countryid) values ('Старо Нагоричане', '1');
insert into PLACE (name_cyrilic, countryid) values ('Пеклани', '1');
insert into PLACE (name_cyrilic, countryid) values ('с.Речица', '1');
insert into PLACE (name_cyrilic, countryid) values ('Стрновац', '1');
insert into PLACE (name_cyrilic, countryid) values ('Гургурница', '1');
insert into PLACE (name_cyrilic, countryid) values ('(преку Росоман)', '1');
insert into PLACE (name_cyrilic, countryid) values ('Церово', '1');
insert into PLACE (name_cyrilic, countryid) values ('Скудриње', '1');
insert into PLACE (name_cyrilic, countryid) values ('Кавадарци', '1');
insert into PLACE (name_cyrilic, countryid) values ('Одри', '1');
insert into PLACE (name_cyrilic, countryid) values ('Берово', '1');
insert into PLACE (name_cyrilic, countryid) values ('Врбјане', '1');
insert into PLACE (name_cyrilic, countryid) values ('с.Велебрдо', '1');
insert into PLACE (name_cyrilic, countryid) values ('Видуше', '1');
insert into PLACE (name_cyrilic, countryid) values ('Новаке', '1');
insert into PLACE (name_cyrilic, countryid) values ('Врбјани', '1');
insert into PLACE (name_cyrilic, countryid) values ('с.Лажани', '1');
insert into PLACE (name_cyrilic, countryid) values ('Жилче', '1');
insert into PLACE (name_cyrilic, countryid) values ('с.Делгожда', '1');
insert into PLACE (name_cyrilic, countryid) values ('Дејловце', '1');
insert into PLACE (name_cyrilic, countryid) values ('Сенокос', '1');
insert into PLACE (name_cyrilic, countryid) values ('СТруга', '1');
insert into PLACE (name_cyrilic, countryid) values ('Велес', '1');
insert into PLACE (name_cyrilic, countryid) values ('Дебар', '1');
insert into PLACE (name_cyrilic, countryid) values ('Валандово', '1');
insert into PLACE (name_cyrilic, countryid) values ('Спанчево', '1');
insert into PLACE (name_cyrilic, countryid) values ('Бучин', '1');
insert into PLACE (name_cyrilic, countryid) values ('Орашје', '1');
insert into PLACE (name_cyrilic, countryid) values ('Трстија', '1');
insert into PLACE (name_cyrilic, countryid) values ('Вирово', '1');
insert into PLACE (name_cyrilic, countryid) values ('Центар Жупа', '1');
insert into PLACE (name_cyrilic, countryid) values ('Македонски Брод', '1');
insert into PLACE (name_cyrilic, countryid) values ('Милино', '1');
insert into PLACE (name_cyrilic, countryid) values ('Озормиште', '1');
insert into PLACE (name_cyrilic, countryid) values ('Вевчани', '1');
insert into PLACE (name_cyrilic, countryid) values ('Пелинце', '1');
insert into PLACE (name_cyrilic, countryid) values ('Н.Село2', '1');
insert into PLACE (name_cyrilic, countryid) values ('Лисиче', '1');
insert into PLACE (name_cyrilic, countryid) values ('Дојран', '1');
insert into PLACE (name_cyrilic, countryid) values ('Копачин Дол', '1');
insert into PLACE (name_cyrilic, countryid) values ('Богомила', '1');
insert into PLACE (name_cyrilic, countryid) values ('Кичево', '1');
insert into PLACE (name_cyrilic, countryid) values ('Мелница', '1');
insert into PLACE (name_cyrilic, countryid) values ('Брајчино', '1');
insert into PLACE (name_cyrilic, countryid) values ('Струга', '1');
insert into PLACE (name_cyrilic, countryid) values ('Радовиш', '1');
insert into PLACE (name_cyrilic, countryid) values ('Кр.Паланка', '1');
insert into PLACE (name_cyrilic, countryid) values ('Отучиште', '1');
insert into PLACE (name_cyrilic, countryid) values ('дебар', '1');
insert into PLACE (name_cyrilic, countryid) values ('Јеловјане', '1');
insert into PLACE (name_cyrilic, countryid) values ('Браилово', '1');
insert into PLACE (name_cyrilic, countryid) values ('Селце кеч', '1');
insert into PLACE (name_cyrilic, countryid) values ('Стража', '1');
insert into PLACE (name_cyrilic, countryid) values ('Св. Николе', '1');
insert into PLACE (name_cyrilic, countryid) values ('Св.Николе', '1');
insert into PLACE (name_cyrilic, countryid) values ('Пехчево', '1');
insert into PLACE (name_cyrilic, countryid) values ('Ох', '1');
insert into PLACE (name_cyrilic, countryid) values ('Железнец', '1');
insert into PLACE (name_cyrilic, countryid) values ('Тетово', '1');
insert into PLACE (name_cyrilic, countryid) values ('Мешеишта', '1');
insert into PLACE (name_cyrilic, countryid) values ('Арачиново', '1');
insert into PLACE (name_cyrilic, countryid) values ('Кучичино', '1');
insert into PLACE (name_cyrilic, countryid) values ('Пробиштип', '1');
insert into PLACE (name_cyrilic, countryid) values ('Воѓани', '1');
insert into PLACE (name_cyrilic, countryid) values ('Крушево', '1');
insert into PLACE (name_cyrilic, countryid) values ('Д.Хисар', '1');
insert into PLACE (name_cyrilic, countryid) values ('Ваташа', '1');
insert into PLACE (name_cyrilic, countryid) values ('Ракитец', '1');
insert into PLACE (name_cyrilic, countryid) values ('Панчарево', '1');
insert into PLACE (name_cyrilic, countryid) values ('Маврови Анови', '1');
insert into PLACE (name_cyrilic, countryid) values ('Гевгелија', '1');
insert into PLACE (name_cyrilic, countryid) values ('Охрид', '1');
insert into PLACE (name_cyrilic, countryid) values ('Волино', '1');
insert into PLACE (name_cyrilic, countryid) values ('Седларево', '1');
insert into PLACE (name_cyrilic, countryid) values ('Могила', '1');
insert into PLACE (name_cyrilic, countryid) values ('Костинци', '1');
insert into PLACE (name_cyrilic, countryid) values ('Демир Хисар', '1');
insert into PLACE (name_cyrilic, countryid) values ('Г.Седларце', '1');
insert into PLACE (name_cyrilic, countryid) values ('Ст. Нагоричане', '1');
