/* 1*/ insert into PLACE (name, name_cyrilic, population, postalcode, countryid) values ('Skopje', 'Скопје', '700000', '1000', '1');
/* 2*/ insert into PLACE (name, name_cyrilic, population, postalcode, countryid) values ('Negotino', 'Неготино', '15000', '1440', '1');
/* 3*/ insert into PLACE (name, name_cyrilic, countryid) values ('Kavadarci', 'Кавадарци', '1');
/* 4*/ insert into PLACE (name, name_cyrilic, countryid) values ('Ohrid', 'Охрид', '1');
/* 5*/ insert into PLACE (name, name_cyrilic, countryid) values ('Veles', 'Велес', '1');
/* 6*/ insert into PLACE (name, name_cyrilic, countryid) values ('Tetovo', 'Тетово', '1');
/* 7*/ insert into PLACE (name, name_cyrilic, countryid) values ('Kumanovo', 'Куманово', '1');
/* 8*/ insert into PLACE (name, name_cyrilic, countryid) values ('Kochani', 'Кочани', '1');
/* 9*/ insert into PLACE (name, name_cyrilic, countryid) values ('Bitola', 'Битола', '1');
/*10*/ insert into PLACE (name, name_cyrilic, countryid) values ('Prilep', 'Прилеп', '1');
/*11*/ insert into PLACE (name, name_cyrilic, countryid) values ('Strumica', 'Струмица', '1');
/*12*/ insert into PLACE (name, name_cyrilic, countryid) values ('Gevgelija', 'Гевгелија', '1');
/*13*/ insert into PLACE (name, name_cyrilic, countryid) values ('Gostivar', 'Гостивар', '1');
/*14*/ insert into PLACE (name, name_cyrilic, countryid) values ('Struga', 'Струга', '1');
/*15*/ insert into PLACE (name, name_cyrilic, countryid) values ('Kichevo', 'Кичево', '1');
/*16*/ insert into PLACE (name, name_cyrilic, countryid) values ('Shtip', 'Штип', '1');
/*17*/ insert into PLACE (name, name_cyrilic, countryid) values ('Resen', 'Ресен', '1');
/*18*/ insert into PLACE (name, name_cyrilic, countryid) values ('Debar', 'Дебар', '1');
/*19*/ insert into PLACE (name, name_cyrilic, countryid) values ('Kriva Palanka', 'Крива Паланка', '1');
/*20*/ insert into PLACE (name, name_cyrilic, countryid) values ('Demir Kapija', 'Демир Капија', '1');
/*21*/ insert into PLACE (name, name_cyrilic, countryid) values ('Valandovo', 'Валандово', '1');
/*22*/ insert into PLACE (name, name_cyrilic, countryid) values ('Bogdanci', 'Богданци', '1');
/*23*/ insert into PLACE (name, name_cyrilic, countryid) values ('Makedonski Brod', 'Македонски Брод', '1');
/*24*/ insert into PLACE (name, name_cyrilic, countryid) values ('Krushevo', 'Крушево', '1');
/*25*/ insert into PLACE (name, name_cyrilic, countryid) values ('Demir Hisar', 'Демир Хисар', '1');
/*26*/ insert into PLACE (name, name_cyrilic, countryid) values ('Radovish', 'Радовиш', '1');
/*27*/ insert into PLACE (name, name_cyrilic, countryid) values ('Delchevo', 'Делчево', '1');
/*28*/ insert into PLACE (name, name_cyrilic, countryid) values ('Berovo', 'Берово', '1');
/*29*/ insert into PLACE (name, name_cyrilic, countryid) values ('Makedonska Kamenica', 'Македонска Каменица', '1');
/*30*/ insert into PLACE (name, name_cyrilic, countryid) values ('Pehchevo', 'Пехчево', '1');
/*31*/ insert into PLACE (name, name_cyrilic, countryid) values ('Kratovo', 'Кратово', '1');
/*32*/ insert into PLACE (name, name_cyrilic, countryid) values ('Sveti Nikole', 'Свети Николе', '1');
/*33*/ insert into PLACE (name, name_cyrilic, countryid) values ('Dojran', 'Дојран', '1');
/*34*/ insert into PLACE (name, name_cyrilic, countryid) values ('Star Dojran', 'Стар Дојран', '1');
/*35*/ insert into PLACE (name, name_cyrilic, countryid) values ('Nov Dojran', 'Нов Дојран', '1');
/*36*/ insert into PLACE (name, name_cyrilic, countryid) values ('Probishtip', 'Пробиштип', '1');
/*37*/ insert into PLACE (name, name_cyrilic, countryid) values ('Vinica', 'ВИНИЦА', '1');