insert into COUNTRY (name, population, countrycode) values ('Macedonia', '2000000', 'MKD');
insert into COUNTRY (name, population, countrycode) values ('Bulgaria', '7000000', 'BGR');
insert into COUNTRY (name, population, countrycode) values ('Serbia', '7000000', 'SRB');
insert into COUNTRY (name, population, countrycode) values ('Albania', '2500000', 'ALB');
insert into COUNTRY (name, population, countrycode) values ('Greece', '11000000', 'GRE');
insert into COUNTRY (name, population, countrycode) values ('Kosovo', '1800000', 'KOS');
insert into COUNTRY (name, population, countrycode) values ('Croatia', '4000000', 'KOS');
insert into COUNTRY (name, population, countrycode) values ('Austria', '8000000', 'AUT');
insert into COUNTRY (name, population, countrycode) values ('Czechia', '10000000', 'CZE');